"""Assemble and compile the manuscript from the generated results.

Emits the generated LaTeX tables from the result CSVs, copies the figures
into ``paper/`` and runs pdflatex.  Usage::

    python scripts/build_paper.py [--no-compile]
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
FIGURES = [
    "fig01_exclusion",
    "fig02_handshake",
    "fig03_invasion",
    "fig04_cliff",
    "fig05_nucleation",
    "fig06_instruments",
    "fig07_channels",
    "fig08_providers",
    "fig09_robustness",
]


def _fmt(value: float, digits: int = 3) -> str:
    return f"{value:.{digits}f}"


def emit_tables() -> None:
    tables = ROOT / "results" / "tables"
    key = json.loads((ROOT / "results" / "key_numbers.json").read_text())

    # ------------------------------------------------------------- main tables
    payoff = pd.read_csv(tables / "race_payoff.csv", index_col=0)
    harm = pd.read_csv(tables / "race_unsafe_count.csv", index_col=0)
    lines = [
        "% generated by scripts/build_paper.py -- do not edit",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{The interaction layer, exactly evaluated over the horizon",
        r"law: expected race payoff $A$ (left) and expected number of unsafe",
        r"actions $M$ (right) of the row design against the column design.",
        r"The row that drives every result is \CAS{} against \CS{}: a first",
        rf"strike earns ${key['payoff_cas_cs']:.2f}$ where the resident earns "
        rf"${key['payoff_cs_cs']:.2f}$ against itself, at the cost of "
        rf"${harm.loc['CAS', 'CS']:.2f}$ unsafe actions, so reciprocity deters it",
        rf"only above $L_R = {key['reciprocity_threshold']:.3f}$.}}",
        r"\label{tab:race}",
        r"\small",
        r"\begin{tabular}{l" + "r" * 4 + "c" + "r" * 4 + "}",
        r"\toprule",
        r" & \multicolumn{4}{c}{payoff $A$} & & \multicolumn{4}{c}{unsafe actions $M$} \\",
        r"\cmidrule{2-5}\cmidrule{7-10}",
        " & " + " & ".join(payoff.columns) + " & & " + " & ".join(harm.columns) + r" \\",
        r"\midrule",
    ]
    for s in payoff.index:
        row_a = " & ".join(_fmt(payoff.loc[s, c], 2) for c in payoff.columns)
        row_m = " & ".join(_fmt(harm.loc[s, c], 2) for c in harm.columns)
        lines.append(rf"{s} & {row_a} & & {row_m} \\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]

    thr = pd.read_csv(tables / "thresholds.csv")
    lines += [
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Closed-form thresholds of the identity layer at zero",
        r"liability.  $\sigma^{*}$ is the spoof success above which the",
        r"unconditional forger invades the certified reciprocator club and",
        r"$\sigma_m$ the threshold for the behavioural mimic, both evaluated",
        r"in a well-mixed population; $r^{*}$ is itself an assortment, the one",
        r"below which no club nucleates whatever the verification.  Note that",
        r"$\sigma_m$ exceeds $\sigma^{*}$ in every row: well mixed, the",
        r"exploiter invades first.  The order reverses above $r = 0.077$",
        r"(Section~\ref{sec:mimicry}), which is why the baseline $r = 0.1$ has",
        r"$\sigma^{*} = 0.962 > \sigma_m = 0.938$ and why the manuscript",
        r"reports the mimic as the first invader.  Dues weaken the club; fines",
        r"strengthen it only through the detections the screen already makes.}",
        r"\label{tab:thresholds}",
        r"\small",
        r"\begin{tabular}{rrrrr}",
        r"\toprule",
        r"dues $\kappa_g$ & fine $\rho$ & $\sigma^{*}$ (forger) & $\sigma_m$ (mimic) & $r^{*}$ \\",
        r"\midrule",
    ]
    for _, row in thr.iterrows():
        lines.append(
            rf"{row.kappa_g:.1f} & {row.rho:.0f} & {_fmt(min(row.sigma_star_forger, 1.0))} "
            rf"& {_fmt(min(row.sigma_star_mimic, 1.0))} & {_fmt(row.r_star)} \\"
        )
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]

    pools = pd.read_csv(tables / "pool_ablation.csv")
    pool_label = {
        "full": "certified world (48 designs)",
        "honest": "unforgeable badges (32)",
        "uncertified": "uncertified world (16)",
        "plain": "raw race (4)",
    }
    lines += [
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{The baseline equilibrium across nested design pools, in the",
        r"small-mutation limit ($\sigma = 0.5$, $r = 0.1$, $\kappa_g = 2$,",
        r"$L = 0$, $Z = 100$, $\beta = 0.05$).  The identity layer roughly",
        r"halves the long-run unsafe frequency of the uncertified world;",
        r"forgery at a coin-flip spoof rate claws back about a quarter of the",
        r"gain that unforgeable badges would deliver.}",
        r"\label{tab:pools}",
        r"\small",
        r"\begin{tabular}{lrrrrr}",
        r"\toprule",
        r"design pool & unsafe & club & falsebeard & integrity & social \\",
        r"\midrule",
    ]
    for _, row in pools.iterrows():
        lines.append(
            rf"{pool_label[row.pool]} & {_fmt(row.unsafe)} & {_fmt(row.club, 2)} & "
            rf"{_fmt(row.falsebeard, 2)} & {_fmt(row.integrity, 2)} & {row.social:.1f} \\"
        )
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]

    prov = pd.read_csv(tables / "provider_frontier.csv")
    lines += [
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{The symmetric $K$-provider world under provider-scoped",
        r"marks.  Cross-provider checks fail, so the ecosystem unsafe",
        r"frequency is $1 - \mathrm{HHI}$ exactly; federated recognition",
        r"plays the club design throughout and is safe at any concentration.",
        r"The exclusion rent is the payoff gap between a member and a",
        r"compliant unbadged entrant.}",
        r"\label{tab:providers}",
        r"\small",
        r"\begin{tabular}{rrrrrr}",
        r"\toprule",
        r"$K$ & HHI & unsafe (scoped) & unsafe (federated) & member & rent \\",
        r"\midrule",
    ]
    for _, row in prov.iterrows():
        if row.providers in (1, 2, 3, 4, 8, 20):
            lines.append(
                rf"{int(row.providers)} & {_fmt(row.hhi, 3)} & {_fmt(row.unsafe_scoped)} & "
                rf"{_fmt(row.unsafe_federated)} & {row.member_payoff:.1f} & "
                rf"{row.exclusion_rent:.1f} \\"
            )
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]

    (ROOT / "paper" / "tables_generated.tex").write_text("\n".join(lines))

    # ------------------------------------------------------- robustness tables
    proc = pd.read_csv(tables / "robustness_process.csv")
    scope = pd.read_csv(tables / "robustness_setback_scope.csv")
    rlines = [
        "% generated by scripts/build_paper.py -- do not edit",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Process robustness of the baseline equilibrium.  Upper",
        r"block: population size and selection intensity.  Lower block: both",
        r"readings of the setback clause of the race, where 'total' means a",
        r"realised setback removes the accumulated stage payoffs as well as",
        r"the prize and 'prize' means it removes only the prize.  The two",
        r"blocks do not share the meaning of the last column, so each carries",
        r"its own header row.}",
        r"\label{tab:robustness}",
        r"\small",
        r"\begin{tabular}{rrrrr}",
        r"\toprule",
        r"$Z$ & $\beta$ & unsafe & club & integrity \\",
        r"\midrule",
    ]
    for _, row in proc.iterrows():
        rlines.append(
            rf"{int(row.population_size)} & {row.beta:g} & {_fmt(row.unsafe)} & "
            rf"{_fmt(row.club, 2)} & {_fmt(row.integrity, 2)} \\"
        )
    rlines += [
        r"\midrule",
        r"setback scope & & certified unsafe & club share & uncertified unsafe \\",
        r"\midrule",
    ]
    for _, row in scope.iterrows():
        rlines.append(
            rf"{row.scope} & & {_fmt(row.unsafe)} & {_fmt(row.club, 2)} & "
            rf"{_fmt(row.uncertified_unsafe)} \\"
        )
    rlines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    (ROOT / "paper" / "robustness_generated.tex").write_text("\n".join(rlines))
    print("emitted tables_generated.tex and robustness_generated.tex")


def stage() -> None:
    dest = ROOT / "paper" / "figures"
    dest.mkdir(parents=True, exist_ok=True)
    missing = []
    for name in FIGURES:
        src = ROOT / "results" / "figures" / f"{name}.pdf"
        if not src.exists():
            missing.append(name)
            continue
        shutil.copy2(src, dest / f"{name}.pdf")
    if missing:
        raise SystemExit(
            "missing figures: " + ", ".join(missing)
            + "\nrun scripts/make_figures.py first"
        )
    print("staged", len(FIGURES), "figures")


def _run(cmd: list[str], allow_fail: bool = False) -> subprocess.CompletedProcess:
    proc = subprocess.run(cmd, cwd=ROOT / "paper", capture_output=True, text=True)
    if proc.returncode != 0 and not allow_fail:
        sys.stdout.write(proc.stdout[-6000:])
        sys.stderr.write(proc.stderr[-2000:])
        raise SystemExit(f"{cmd[0]} failed with code {proc.returncode}")
    return proc


def compile_pdf() -> None:
    tex = ["pdflatex", "-interaction=nonstopmode", "-halt-on-error", "main.tex"]
    _run(tex)
    _run(["bibtex", "main"], allow_fail=True)
    _run(tex)
    proc = _run(tex)
    for line in proc.stdout.splitlines():
        if "Output written" in line:
            print(line.strip())


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--no-compile", action="store_true")
    args = parser.parse_args()
    emit_tables()
    stage()
    if not args.no_compile:
        compile_pdf()
